#!/usr/bin/env bash
# Function to display subdomain information
display_info() {
    local subdomain="$1"
    local record_type="$2"
    local destination="$3"
    echo "The subdomain $subdomain is a $record_type record and points to $destination"
}

# Domain and subdomain information
domain="$1"
subdomain="$2"

# Default subdomains to check
subdomains=("www" "lb-01" "web-01" "web-02")
if [ "$#" == 1 ]; then
    # Loop through subdomains
    for sub in "${subdomains[@]}"; do
        # Use dig command to get DNS information and awk for parsing
        record_type=$(dig +short -t CNAME "$sub.$domain" | awk '/CNAME/{print $1}')
        destination=$(dig +short -t A "$sub.$domain" | awk 'NR==1{print $1}')

        # Display information
        display_info "$sub.$domain" "$record_type" "$destination"
    done
else
    # Check if a specific subdomain is provided
    if [ -n "$subdomain" ]; then
        # Use dig command to get DNS information for the specific subdomain
        record_type=$(dig +short -t CNAME "$subdomain.$domain" | awk '/CNAME/{print $1}')
        destination=$(dig +short -t A "$subdomain.$domain" | awk 'NR==1{print $1}')

        # Display information for the specific subdomain
        display_info "$subdomain.$domain" "$record_type" "$destination"
    fi
fi
