#!/usr/bin/env bash

# Use 'ip' command to list all network interfaces and their IP addresses,
# filter for IPv4 addresses, and format the output using 'awk'.

ip -4 -o addr show | awk '/inet / {print $4}' | cut -d "/" -f 1
