#!/usr/bin/env bash
# Run the whoami command under the user passed as an argument

argument="$1"

if [ "$#" == 1 ]; then
    sudo -u "$argument" whoami
else
    echo "Invalid usage. Provide exactly one argument."
fi
